### ISSUE TITLE
Post with params in body problem.

### ISSUE THREAD

**Issue by pagusek** [michaelyaakoby/testfun#14]
Hi Michael, I’ve written a very simple web service:

```
@POST
@Path("test")
public Response createUser(@FormParam("name") String name)
{
    return Response.status(Status.OK).entity(name).build();
}

```
When I deploy in WildFly 9 and call it with “name=Jack” in the request body, I get a reply body “Jack”. So everything works as expected.

But when I try to test it with:

```
@XmlRootElement
@XmlAccessorType(XmlAccessType.PROPERTY)
@NoArgsConstructor
@AllArgsConstructor
@Data
public class CreateUserHttpBodyParams
{
	private String name;
}
```

and

`assertEquals("Jack", jaxRsServer.jsonRequest("api/v1/users/test").body(new CreateUserHttpBodyParams("Jack")).expectStatus(Status.OK).post());`

I get: org.junit.ComparisonFailure: expected:<[Jack]> but was:<[]>

Thank you very much for any tips!
Jack

**Comment by michaelyaakoby** [comment]
When using `.jsonRequest(...)` you are telling testfun that the body is JSON. 

You can create your own `RestRequest` and then specify the correct type - I've added a test that demonstrate this, so update your copy of testfun.

The test code looks like:
```
@Test
public void postWithForm() throws Exception {
      String response = new RestRequest("/example/form", jaxRsServer.getPort()).
            accept(MediaType.APPLICATION_FORM_URLENCODED_TYPE).
            body("p1=ABCD&p2=12345").
            expectStatus(Response.Status.OK).
            post();
    assertEquals("ABCD-12345", response);
}
```

**Comment by pagusek** [comment]
Thank you very much for your help. I'd like to recommend that library for everyone :)

**Comment by bdimitrov2** [comment]
Hi Michael, I'm working together with Jack, and your proposal works for us, so thank you very much!

If you'd like to make the usage a bit more friendly, you could set up something like `.jsonRequest(...)`:

`jaxRsServer.restRequest("api/v1/users/test").body("param1=a&param2=b").expectStatus(Status.OK).post();`

the `.accept(MediaType.APPLICATION_FORM_URLENCODED_TYPE)` does not need to mentioned in the setup above since it's always necessary. That would be great, of course, but I can also live with your proposed solution.

Once again, thanks for a great test framework!

**Comment by michaelyaakoby** [comment]
Glad you love it - thanks for the feedback.

How about something like:
```java
String response = jaxRsServer.
        formRequest("/example/form").
        withFormParam("p1", "ABCD").
        withFormParam("p2", "12345").
        expectStatus(Response.Status.OK).
        post();
```

**Comment by gitfan13** [comment]
Michael, I like it a lot!

In addition to `withFormParam()` you might also want to consider `withFormParams("p1=ABCD&p2=12345")`, but that's not a must.

Thanks in advance :-)
